"""auto_votes_table

Revision ID: 46c504aaa166
Revises: 
Create Date: 2022-12-26 11:13:48.759215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c504aaa166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votedata',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['postdata.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['userdata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('votedata')
  
